# Generated by Django 6.0.1 on 2026-01-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пословицы')),
                ('meaning', models.TextField(verbose_name='Значение (пояснение)')),
                ('origin', models.CharField(blank=True, default='Народная', max_length=200, verbose_name='Происхождение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proverbs', to='ProverbsApp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пословица',
                'verbose_name_plural': 'Пословицы',
            },
        ),
    ]
