# Generated by Django 5.0.9 on 2026-03-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProverbsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proverb',
            name='category',
        ),
        migrations.AddField(
            model_name='proverb',
            name='categories',
            field=models.ManyToManyField(related_name='proverbs', to='ProverbsApp.category', verbose_name='Категории'),
        ),
    ]
