# Generated by Django 5.0.9 on 2026-04-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProverbsApp', '0002_remove_proverb_category_proverb_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proverb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пословица', 'verbose_name_plural': 'Пословицы'},
        ),
        migrations.AddField(
            model_name='proverb',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_proverbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proverb',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Пословица дня'),
        ),
        migrations.AddField(
            model_name='proverb',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_proverbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proverb',
            name='status',
            field=models.CharField(choices=[('approved', 'Одобрено'), ('pending', 'На модерации'), ('rejected', 'Отклонено')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='proverb',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='proverbs', to='ProverbsApp.category', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proverb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ProverbsApp.proverb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
